# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'kannan-kozhavur-padmanabhan28899'
    scannerMode: 'MSBuild'
    projectKey: 'question'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
    #codeCoverageEnabled: True


- task: SonarCloudAnalyze@1

- task: CoverageConverter@0
  inputs:
    searchFolderForTestFiles: '$(System.DefaultWorkingDirectory)'
    vsTestExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe'
    vsTestArgs: '/EnableCodeCoverage'
    listTestFiles: '**\bin\**\*.Tests*.dll'
    searchFolderForCodeCoverageFile: '$(System.DefaultWorkingDirectory)'
    temporaryFolderForCodeCoverage: 'Agent.TempDirectory'
    temporaryFileCoveragexml: '\TestResults\DynamicCodeCoverage.coveragexml'
    codeCoverageArgs: 'analyze /output:'
    codeCoverageExeFileLocation: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe'

- task: reportgenerator@4
  inputs:
    reports: '$(Agent.TempDirectory)\TestResults\DynamicCodeCoverage.coveragexml'
    targetdir: '$(Agent.TempDirectory)\TestResults'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Agent.TempDirectory)\TestResults\Cobertura.xml'
    reportDirectory: '$(Build.SourcesDirectory)/CodeCoverage'
  
- task: ResharperCli@2
  inputs:
    solutionOrProjectPath: '$(System.DefaultWorkingDirectory)\Casestudy1.sln'
    failBuildLevelSelector: 'Warning'
    failBuildOnCodeIssues: false
    additionalArguments: '/disable-settings-layers:SolutionPersonal --properties:Configuration=$(Build.Configuration)'


- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'